export const SET_USER_NAME = "SET_USER_NAME";

export const LOADER = {
  SHOW: "SHOW_LOADER",
  HIDE: "HIDE_LOADER",
};

export const MESSAGE = {
  DISPLAY: "DISPLAY_MESSAGE",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  CLEAN_ERROR: "CLEAN_ERROR",
  WRONG_DATA: "WRONG_DATA",
  NETWORK_ERROR: "NETWORK_ERROR",
  WRONG_LOGIN_CREDENTIALS: "WRONG_LOGIN_CREDENTIALS",
  ACCESS_DENIED: "ACCESS_DENIED",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
};
export const TOOLS = {
  ADD_TOOLS: "ADD_TOOLS",
  ADD_MANDATORY: "ADD_MANDATORY"
};


export const ORG_USERS ={
  ADD: "ADD_USERS_TO_ORG",
  EDIT: "EDIT_ORG_USERS",
  DELETE: "DELETE_ORG_USERS",
  BULK_ADD: "BULK_ADD_ORG_USERS",
  GET_ORG_USERS: "GET_ORG_USERS",
}

export const TOOL = {
  ADD: "ADD_TOOL",
  EDIT: "EDIT_TOOL",
  DELETE: "DELETE_TOOL",
  GET_TOOL: "GET_TOOL"
};
export const Org = {
  ADD_DATA: "ADD_DATA",
};


export const PROJECT_ONBOARD = {
  BASIC_DETAILS: {
    PROJECTNAME: "PROJECTNAME",
    ADD_DETAILS: "ADD_DETAILS",
    DEFINITION: "DEFINITION",
    TOOLS: "TOOLS",
    TOOLS_DETAILS: "TOOLS_DETAILS",
    JIRA: "JIRA",
    BITBUCKET: "BITBUCKET",
    TEAMS: "TEAMS",
    RESET_STEPPER: "RESET_STEPPER",
  },
  USERS: {
    ADD_MEMBER: "ADD_MEMBER",
    EDIT_MEMBER: "EDIT_MEMBER",
    DELETE_MEMBER: "DELETE_MEMBER",
    NEW_MEMBER: "NEW_MEMBER",
    RESET_MEMBER: "RESET_MEMBER",
  },
  API: {
    SAVE_AS_DRAFT: "SAVE_AS_DRAFT",
  },
  EVENTS: {
    PROVISION: "PROJECTS_PROVISIONING",
  }
};

export const USERS = {
  GET_USERS: "GET_USERS",
  GET_USER_BY_EMAIL: "GET_USER_BY_EMAIL"
}
export const PROJECT_DATA = {
  GET_PROJECT: "GET_PROJECT"
};

export const ACTION_TYPES = {
  SET_FORM_VALUE: "SET_FORM_VALUE",
};

export const TOOL_ROLES={
  GET_TOOL_ROLES: "GET_TOOL_ROLES",
  ADD_TOOL_ROLES: "ADD_TOOL_ROLES",
  EDIT_TOOL_ROLES: "EDIT_TOOL_ROLES",
  DELETE_TOOL_ROLES: "DELETE_TOOL_ROLES" 
}


// AUTHENTICATION

export const LOGOUT = "LOGOUT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

// USERS
export const GET_USER_BY_USERNAME = "GET_USER_BY_USERNAME";

//INITIAL_CREATE
export const INITIAL_CREATE = "INITIAL_CREATE";
export const TOAST={
  DELETE_SUCCESS: "Deleted Successfully!!",
  UPDATE_SUCCESS: "Updated Successfully!!",
  ADD_SUCCESS: "Created Successfully!!",
}

export const BITBUCKET = {
  GET_BITBUCKET_DATA : "GET_BITBUCKET_DATA"
}

export const JIRA = {
  GET_JIRA_DATA: "GET_JIRA_DATA"
}